# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

#- script: dotnet build --configuration $(buildConfiguration) --output $(build.ArtifactStagingDirectory)
steps:
#- powershell: .\build.ps1
- task: CopyFiles@2
  inputs:
    contents: '_buildOutput\**'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs
  displayName: 'dotnet build $(buildConfiguration)'
